# Generated by Django 5.0.7 on 2024-07-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('decription', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('Githublink', models.URLField()),
                ('DemoLink', models.URLField()),
            ],
        ),
    ]
