# Generated by Django 5.0.7 on 2024-07-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='DemoLink',
            new_name='github_link',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='Githublink',
        ),
        migrations.AddField(
            model_name='projects',
            name='demo_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
